/**
 * THE DENOMINATOR. Spec §20's "100% byte-identical" is meaningless until this file says what of.
 *
 * ---
 *
 * ## The set
 *
 * Two parts, and they do different jobs. Both are in the denominator; neither is sufficient alone.
 *
 * **`probes/` — 42 hand-built fixtures, one per markdown construct.** Committed, deterministic,
 * synthetic. They exist so coverage is *guaranteed* rather than sampled: a construct that appears in
 * eleven files of a real tree can be missed by any sample, and the constructs most likely to be
 * missed are the rare ones, which are exactly the ones nobody thought about. This is what the build
 * plan means by "graduate `probes/` into the permanent corpus."
 *
 * **`corpus/` — a construct-covering sample of the mock soil.** Regenerated by `scan-corpus.cjs`,
 * **not committed**. It exists because probes are clean and real documents are not: constructs in
 * combination, at realistic length, with the incidental mess that only accumulates. A probe proves
 * a table survives; the corpus proves a table survives inside a 400-line document that also has
 * frontmatter, three fences and a footnote.
 *
 * The tree it samples is the **mock soil** — ruled 2026-08-08: *"this is why we have a
 * fake soil."* It carries the real tree's measured construct distribution.
 *
 * ## What is excluded, and why exclusion is stated rather than assumed
 *
 * **Files whose bytes are not valid UTF-8 are excluded from the round-trip denominator** and
 * reported by name. §12 requires the app to *refuse* them, so refusing is correct behaviour and not
 * a failure — and the driver hands the editor a decoded string, so their actual bytes never reach
 * it and no honest pass/fail can be recorded. The real tree contains two such files. See
 * `compare.cjs`.
 *
 * Nothing else is excluded. Empty files count. Large files count.
 *
 * ## The baseline this must reproduce
 *
 * The old editor over the real tree returned **4 of 1,611 byte-identical, three of them empty — one
 * real file** — and that number did not move after every missing TipTap extension was installed,
 * which is what proved the damage structural.
 *
 * **That number cannot be reproduced digit-for-digit and should not be quoted as a target**, for two
 * reasons, both recorded rather than discovered later:
 *
 *   1. It was measured with a **decoded-string comparison**, which this phase replaced.
 *   2. It was measured on a **snapshot of the real tree that no longer exists** — and the tree has
 *      since grown from 1,611 markdown files to over 4,600.
 *
 * What must be reproduced is the **finding**: run against the old editor, this corpus comes back
 * overwhelmingly damaged, and the damage is per-construct rather than incidental. An instrument that
 * reports the old editor as harmless is broken, and that is the check — not a digit.
 */
const fs = require('node:fs')
const path = require('node:path')

const { S } = require('./where.cjs')

const PROBES = path.join(S, 'probes')
const SAMPLE = path.join(S, 'corpus')

/** Every file in the denominator, as `{ group, name, file }`. Sorted, so a run is reproducible. */
function denominator() {
  const out = []
  for (const [group, dir] of [['probe', PROBES], ['corpus', SAMPLE]]) {
    let names
    try {
      names = fs.readdirSync(dir).filter(n => n.endsWith('.md')).sort()
    } catch {
      /**
       * **Loud, and it must be.** A missing directory returning an empty list would silently shrink
       * the denominator to whichever half survived — and the percentage would go *up*. That is the
       * harness's version of §6's empty-but-successful result, in the one number this build treats
       * as authoritative.
       */
      throw new Error(
        `${group} directory missing: ${dir}\n` +
        (group === 'corpus'
          ? 'regenerate it with:  npm run harness:corpus'
          : 'probes are committed source — this should not happen'))
    }
    if (names.length === 0) {
      throw new Error(`${group} directory is empty: ${dir}`)
    }
    for (const name of names) out.push({ group, name, file: path.join(dir, name) })
  }
  return out
}

/** Reads the denominator as BYTES. Never a decoded string — see `compare.cjs` for why. */
function readAll() {
  return denominator().map(entry => ({
    ...entry,
    path: `${entry.group}/${entry.name}`,
    bytes: fs.readFileSync(entry.file),
  }))
}

module.exports = { PROBES, SAMPLE, denominator, readAll }
