/**
 * THE MOCK SOIL GENERATOR — and the refusals that keep it away from the user's real files.
 *
 * This module writes a tree and, to rebuild one, **removes a tree recursively**. That is the one
 * operation in this repository capable of reproducing the original disaster, and it lives here
 * for the same reason `src/core/fs/staging.ts` holds the app's only recursive delete: one place,
 * heavily guarded, tested by trying to break it.
 *
 * The guards are not decoration. The operator's standing rule is *"before we do anything to actual
 * soil files please let me know"* — so this tool is built such that pointing it at their tree is
 * **not something it can be talked into**, by a typo, an argument, or an environment variable.
 *
 * ## What it refuses, and why each one is a real accident and not a hypothetical
 *
 * | Refusal | The accident it stops |
 * |---|---|
 * | A relative path | `mock-soil ../..` resolved against whatever the shell's cwd happened to be |
 * | Anything inside the repository | the obvious typo: the tree is *generated from inside* the repo |
 * | Any ancestor of the repository | `~` — wiping it takes the soil with it |
 * | The home directory itself | same, one keystroke shorter |
 * | Fewer than three path segments | `/Users`, `/opt`, `/` |
 * | A symlink at the target | the link is removed, or the write travels through it |
 * | An existing directory without our marker | **the big one** — pointing it at any real folder |
 *
 * The repository root is *discovered* from this file's own location rather than hardcoded, so the
 * protection follows the code if the repo ever moves. A hardcoded string protects the path it was
 * written for; this protects whatever tree it is actually living in.
 */

import { promises as fsp } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  bulkDirectories, bulkFiles, DEEP_FILE, HAZARD_FILES, SPECIAL_ENTRIES, SPINE_FILES,
  type PlainFile, type SpecialEntry,
} from './tree.ts'

/** The file that marks a directory as ours. Its presence is what licenses removal. */
export const MARKER = '.soil-viewer-mock'

/** Written into the marker so a future reader knows what they found. */
const MARKER_BODY = `This directory was generated by the Soil Viewer build as a MOCK tree.

Nothing in it is real. It exists so the app can be tested against realistic files without going
anywhere near the user's actual soil. It is disposable: "npm run mock:soil" deletes and rebuilds it.

The generator will refuse to delete any directory that does not contain this file. Do not remove
it and then wonder why the tool stopped working — that refusal is the safety property.

Generator: app/test/support/mock-soil/
`

export interface Refusal { readonly ok: false; readonly reason: string }
export interface Allowed { readonly ok: true }
export type Verdict = Refusal | Allowed

const refuse = (reason: string): Refusal => ({ ok: false, reason })

/**
 * Splits a POSIX absolute path into segments. Comparison is **whole-segment** throughout this
 * module — spec §5, and the reason is the same bug it names: a raw prefix test makes
 * `/Users/hallberg/notes-mock` look like it is inside `/Users/hallberg/notes`.
 */
const segmentsOf = (absolute: string): string[] => absolute.split(sep).filter(Boolean)

/** True when `inner` is `outer` or sits beneath it, compared segment by segment. */
function isAtOrBelow(inner: string, outer: string): boolean {
  const a = segmentsOf(inner)
  const b = segmentsOf(outer)
  if (a.length < b.length) return false
  return b.every((segment, i) => a[i] === segment)
}

/**
 * The repository this file lives in, found by walking up to the directory holding `.git`.
 * Falls back to the app directory's grandparent, which is still inside the repo — a wrong answer
 * here must err towards refusing more, never less.
 */
export async function findRepositoryRoot(from = dirname(fileURLToPath(import.meta.url))): Promise<string> {
  let current = from
  for (;;) {
    try {
      const stats = await fsp.stat(join(current, '.git'))
      if (stats.isDirectory() || stats.isFile()) return current
    } catch { /* keep walking */ }
    const parent = dirname(current)
    if (parent === current) break
    current = parent
  }

  /**
   * **No `.git` anywhere above us — fall back to the structural root, never to `from`.**
   *
   * This used to `return from`, which is *this file's own directory*, four levels inside the
   * repository. `checkTarget` then only refused targets inside `test/support/mock-soil`, so a tree
   * written at the repository top passed the guard that exists to forbid exactly that. **Verified
   * on 2026-09-01: it allowed one, and 1,637 generated files sat in a checkout awaiting release.**
   *
   * A `.git` directory is the normal case and is why nobody saw this. It is absent in precisely the
   * two situations where the guard matters most: a copy taken without history, and a source archive
   * downloaded rather than cloned.
   *
   * The fallback is derived from this file's known position — `<root>/app/test/support/mock-soil` —
   * so it is correct without git and wrong only if the file moves, which would break the import
   * paths around it long before it reached here.
   */
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..')
}

/**
 * Decides whether `target` may be created and, on a rebuild, destroyed.
 *
 * Takes `repositoryRoot` and `home` as parameters rather than reading them, so the refusals can
 * be tested against a temporary tree instead of against the real repository — a guard that can
 * only be exercised by aiming it at the thing it protects is a guard nobody exercises.
 */
export async function checkTarget(
  target: string,
  repositoryRoot: string,
  home: string = homedir(),
): Promise<Verdict> {
  if (!target.startsWith(sep)) {
    return refuse(`the target must be an absolute path, and "${target}" is not — a relative path resolves against whatever directory the shell happened to be in`)
  }

  const segments = segmentsOf(target)
  if (segments.length < 3) {
    return refuse(`"${target}" is too close to the root of the filesystem — the mock tree needs at least three path segments so a mistake cannot reach somewhere important`)
  }

  if (target === home || isAtOrBelow(home, target)) {
    return refuse(`"${target}" is your home directory or contains it — rebuilding the mock tree deletes it first, and this one is not disposable`)
  }

  if (isAtOrBelow(target, repositoryRoot)) {
    return refuse(`"${target}" is inside the repository at "${repositoryRoot}" — the mock tree must live outside it, so it can never be committed and so a path mistake has to leave the folder before it can reach anything real`)
  }

  if (isAtOrBelow(repositoryRoot, target)) {
    return refuse(`"${target}" contains the repository at "${repositoryRoot}" — deleting it would take the repository with it`)
  }

  // lstat, never stat: a symlink at the target must be seen as a symlink. Following it is how a
  // "delete the mock tree" becomes a delete of whatever it points at.
  let entry
  try {
    entry = await fsp.lstat(target)
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code
    if (code === 'ENOENT') return { ok: true } // does not exist yet; we will create it
    return refuse(`could not inspect "${target}": ${code ?? String(error)}`)
  }

  if (entry.isSymbolicLink()) {
    return refuse(`"${target}" is a symlink — the mock tree must be a real directory, or a rebuild follows the link and deletes something else`)
  }
  if (!entry.isDirectory()) {
    return refuse(`"${target}" exists and is not a directory`)
  }

  try {
    await fsp.stat(join(target, MARKER))
  } catch {
    return refuse(`"${target}" already exists and does not contain a "${MARKER}" file, so it was not created by this tool. Refusing to touch it. If you genuinely want the mock tree here, delete the directory yourself first.`)
  }

  return { ok: true }
}

// ---------------------------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------------------------

async function writePlain(root: string, [relative, body]: PlainFile): Promise<void> {
  const full = join(root, relative)
  await fsp.mkdir(dirname(full), { recursive: true })
  await fsp.writeFile(full, body, 'utf8')
}

/** Filler that compresses badly and reads as prose, so a 2 MiB file is not 2 MiB of one letter. */
function filler(size: number): Buffer {
  const unit = 'The intake curve is contractual, not meteorological, and the line runs at 3,400. '
  const header = '# A large document\n\nEverything below is filler to reach an exact size.\n\n'
  const needed = size - Buffer.byteLength(header, 'utf8') - 1
  const body = unit.repeat(Math.ceil(needed / unit.length)).slice(0, needed)
  return Buffer.from(`${header}${body}\n`, 'utf8')
}

async function writeSpecial(root: string, entry: SpecialEntry): Promise<void> {
  const full = join(root, entry.path)
  const kind = entry.kind

  if (kind.type === 'empty-dir' || kind.type === 'dir-mode') {
    await fsp.mkdir(full, { recursive: true })
    if (kind.type === 'dir-mode') await fsp.chmod(full, kind.mode)
    return
  }

  await fsp.mkdir(dirname(full), { recursive: true })

  switch (kind.type) {
    case 'bytes':
      await fsp.writeFile(full, Buffer.from(kind.bytes))
      return
    case 'filled':
      await fsp.writeFile(full, filler(kind.size))
      return
    case 'symlink':
      // The escaping link is absolute; the rest are relative so the tree stays self-contained
      // and can be moved without every link inside it going stale.
      await fsp.symlink(kind.target, full)
      return
    case 'mode':
      await fsp.writeFile(full, kind.body, 'utf8')
      await fsp.chmod(full, kind.mode)
      return
    case 'hardlink':
      await fsp.link(join(root, kind.to), full)
      return
  }
}

export interface BuildReport {
  readonly root: string
  readonly spine: number
  readonly bulk: number
  readonly hazards: number
  readonly special: number
  readonly files: number
  readonly directories: number
  readonly bytes: number
}

/**
 * Builds the tree at `target`. Refuses per `checkTarget`, and **throws rather than returning a
 * value on refusal** — a caller that ignores a returned error still gets stopped.
 */
export async function makeMockSoil(
  target: string,
  options: { readonly repositoryRoot?: string; readonly home?: string; readonly seed?: number } = {},
): Promise<BuildReport> {
  const repositoryRoot = options.repositoryRoot ?? await findRepositoryRoot()
  const verdict = await checkTarget(target, repositoryRoot, options.home)
  if (!verdict.ok) throw new Error(`Refusing to build the mock tree: ${verdict.reason}`)

  await removeMockSoil(target, { repositoryRoot, ...(options.home ? { home: options.home } : {}) })

  await fsp.mkdir(target, { recursive: true })
  // The marker goes down FIRST. If the build dies half way, the next run can still clean up —
  // without it the partial tree would be an unmarked directory the tool then refuses to touch.
  await fsp.writeFile(join(target, MARKER), MARKER_BODY, 'utf8')

  const bulk = bulkFiles(options.seed ?? 20260808)
  const plain: PlainFile[] = [...SPINE_FILES, ...bulk, ...HAZARD_FILES, DEEP_FILE]
  for (const file of plain) await writePlain(target, file)
  // After the files, so a scaffold folder that a document also happens to fill is not disturbed.
  for (const relative of bulkDirectories()) {
    await fsp.mkdir(join(target, relative), { recursive: true })
  }
  for (const entry of SPECIAL_ENTRIES) await writeSpecial(target, entry)

  const counted = await measure(target)
  return {
    root: target,
    spine: SPINE_FILES.length,
    bulk: bulk.length,
    hazards: HAZARD_FILES.length + 1,
    special: SPECIAL_ENTRIES.length,
    ...counted,
  }
}

/** Walks the finished tree and counts it, without following symlinks. */
async function measure(root: string): Promise<{ files: number; directories: number; bytes: number }> {
  let files = 0
  let directories = 0
  let bytes = 0

  const walk = async (dir: string): Promise<void> => {
    let entries
    try {
      entries = await fsp.readdir(dir, { withFileTypes: true })
    } catch {
      return // an unreadable directory is one of the hazards; counting is not worth failing over
    }
    for (const entry of entries) {
      const full = join(dir, entry.name)
      if (entry.isSymbolicLink()) { files += 1; continue }
      if (entry.isDirectory()) { directories += 1; await walk(full); continue }
      files += 1
      try { bytes += (await fsp.lstat(full)).size } catch { /* unreadable, already counted */ }
    }
  }

  directories += 1
  await walk(root)
  return { files, directories, bytes }
}

// ---------------------------------------------------------------------------------------------
// Removal — the dangerous half
// ---------------------------------------------------------------------------------------------

/**
 * Removes the tree at `target`, and **only** if `checkTarget` allows it and the marker is present.
 *
 * The marker check is repeated here rather than trusted from the caller. `checkTarget` runs at the
 * top of the build and this function is also public; a guard that only fires on one of two entry
 * points is the build's signature failure shape — *a control correct in isolation and never
 * reached*.
 *
 * Some of the hazards deliberately make themselves hard to delete: a directory at mode 0555 does
 * not permit its own children to be unlinked. The mode restoration below is what makes the tree
 * disposable, and it is confined to a tree already proven to carry the marker.
 */
export interface RemoveOptions {
  readonly repositoryRoot?: string
  readonly home?: string
  /**
   * **Test seam.** Runs after `checkTarget` and before the marker is confirmed — the only way
   * into the window the second marker check defends.
   *
   * It exists because a mutation sweep found that check GREEN: `checkTarget` already refuses any
   * existing directory without a marker, so in ordinary operation the second check is never the
   * one that fires, and deleting it changed nothing the tests could see. A control that cannot be
   * reached cannot be proven, and an unprovable control on a recursive delete is not a control —
   * it is a comment. Same pattern, and same reason, as `readBack` in
   * `src/core/fs/resolve-conflict.ts`.
   */
  readonly beforeMarkerCheck?: () => Promise<void>
}

export async function removeMockSoil(target: string, options: RemoveOptions = {}): Promise<boolean> {
  const repositoryRoot = options.repositoryRoot ?? await findRepositoryRoot()
  const verdict = await checkTarget(target, repositoryRoot, options.home)
  if (!verdict.ok) throw new Error(`Refusing to remove: ${verdict.reason}`)

  try {
    await fsp.lstat(target)
  } catch {
    return false // nothing there
  }

  if (options.beforeMarkerCheck) await options.beforeMarkerCheck()

  // Confirmed here explicitly rather than inferred from the verdict. `checkTarget` returns ok for
  // a path that does not exist yet, and its own marker check ran before the `lstat` above — so
  // between the two, the marker can go away. On a function that recursively deletes, the second
  // look is worth its cost.
  try {
    await fsp.stat(join(target, MARKER))
  } catch {
    throw new Error(`Refusing to remove "${target}": no "${MARKER}" file at the moment of removal. This tool only deletes trees it created.`)
  }

  await restoreModes(target)
  await fsp.rm(target, { recursive: true, force: true })
  return true
}

/** Makes every directory in the tree traversable and writable again, so removal can proceed. */
async function restoreModes(dir: string): Promise<void> {
  try {
    await fsp.chmod(dir, 0o755)
  } catch { /* best effort */ }
  let entries
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue
    if (entry.isDirectory()) await restoreModes(join(dir, entry.name))
  }
}
