/**
 * THE MOCK SOIL — what is in it, and why each thing is there.
 *
 * ruled 2026-08-08: *"we can use real files that are not my actual files we can build like a
 * mock set or a copy of a folder and put it somewhere for testing purposes and if it fucks up it
 * fucked up."* This is that. It is the tree the app gets pointed at, driven through, and abused.
 * **Their real soil is never the target of anything in this build.**
 *
 * It is a *generator*, not a committed directory, for the same reason the grammar fixture is:
 * the generator is readable and a directory of 1,500 files is not. It is also **deterministic** —
 * no clock, no `Math.random` — so a path referenced in a test or a note keeps meaning the same
 * file next week.
 *
 * ## Three layers, and they answer different questions
 *
 * 1. **The spine** — hand-written documents in a fictional domain (an orchard co-operative), with
 *    real prose, real headings, real tables. Answers *"does a document look right on a screen?"*
 *    The domain is deliberately nothing like the user's actual work, so a mock file can never be
 *    mistaken for a real one at a glance.
 * 2. **The bulk** — generated documents that bring the tree to the scale of the real thing.
 *    Measured on the real soil 2026-08-08: **1,567 markdown files, 1,822 directories, 16 levels
 *    deep, median 2.2 KB, largest 71 KB.** Answers *"does it hold up at the size it will actually
 *    meet?"* — a tree of forty files proves nothing about indexing, watching or scrolling.
 * 3. **The hazards** — `zz-hazards/`, one folder per nasty case. Answers *"what happens when the
 *    filesystem is not polite?"* This is the layer worth the most: every one of these is a shape
 *    that exists in the wild, and each is a plausible way to lose a file.
 */

/** A plain file: folder-relative path, and its exact bytes. */
export type PlainFile = readonly [path: string, body: string]

/**
 * A hazard the generator must build with something other than `writeFile` — a symlink, a hard
 * link, a mode change, raw non-UTF-8 bytes, a file too large to sit in this source file.
 */
export interface SpecialEntry {
  readonly path: string
  /** Plain language, shown by `--list`. This is what the hazard is *for*. */
  readonly why: string
  readonly kind:
    | { readonly type: 'bytes'; readonly bytes: readonly number[] }
    | { readonly type: 'filled'; readonly size: number; readonly unit: string }
    | { readonly type: 'symlink'; readonly target: string; readonly relative: boolean }
    | { readonly type: 'hardlink'; readonly to: string }
    | { readonly type: 'mode'; readonly body: string; readonly mode: number }
    | { readonly type: 'dir-mode'; readonly mode: number }
    | { readonly type: 'empty-dir' }
}

// ---------------------------------------------------------------------------------------------
// 1 · THE SPINE
// ---------------------------------------------------------------------------------------------

const README = `# This is not your soil

**Everything in this folder is fake.** It was generated by the Soil Viewer build so the app has
something realistic to be tested against without going anywhere near your real files.

It is about a made-up orchard co-operative. Nothing here is yours, nothing here matters, and if
the app corrupts every file in this tree that is a *good outcome* — it means we found the bug
here instead of there.

## If you are poking at this

- **Break it on purpose.** Rename things, move things, save the same file from two windows.
- \`zz-hazards/\` is the interesting part. Every folder in it is a way filesystems misbehave —
  strange filenames, files that are too big, files that are not really files. Open them and see
  what the app does. It should refuse clearly, never silently.
- To throw it away and start over, run \`npm run mock:soil\` again. It rebuilds from scratch.

## What it is shaped like

The same shape as your soil — \`00-context\`, \`01-internal\`, \`02-projects\` with projects nested
inside projects, inboxes, task lanes, archives — and roughly the same size: about fifteen hundred
documents across eighteen hundred folders. It was measured against yours so the app meets the
scale it will actually have to handle.
`

const SPINE: readonly PlainFile[] = [
  ['README.md', README],

  // --- 00-context: the walk-up, mirrored -----------------------------------------------------
  ['00-context/context.md', `# Windfall Orchard Co-operative

A fictional tree, standing in for a real one. Eleven member farms in the Annapolis Valley, one
shared packing house, one shared cold store, and a great deal of disagreement about cider.

## How this place is laid out

| Folder | What lives there |
|--------|------------------|
| \`00-context/\` | What the co-op is and how it works |
| \`01-internal/\` | Standards, the bridge, food-safety |
| \`02-projects/\` | The actual work — everything is a project, and projects nest |
| \`03-execution-environments/\` | Pipelines and the machinery that runs them |
| \`04-experiments-and-research/\` | Trials, staging, things not yet real |
| \`99-inbox-main/\` | Anything with no home yet |
| \`archive/\` | Nothing is deleted; it moves here |

## The one rule

A member farm's own records are theirs. The co-op holds the shared record only — grading, cold
store allocation, the packing schedule, and whatever the board has actually voted on.
`],

  ['00-context/conventions/universal-conventions.md', `# Universal Conventions

- Kebab-case for files and folders.
- The path is the metadata. No front-matter on new documents.
- Dates in the text, written out: *14 March 2026*, not \`2026-03-14\` in a header field.
- A document under 500 lines. Longer means it is two documents wearing a coat.

## Naming

\`m-thread-<name>.md\` for a management thread. \`d-thread-<name>.md\` for a discovery thread.
Round tables are \`RT1\`, \`RT2\`, and their record is \`00-context/m-thread-RT<n>.md\`.

## What "done" means

Done is a location, not a checkbox. A finished thing sits in \`archive/\`. If it is still in
\`02-work/\`, it is not finished, whatever the document says about itself.
`],

  ['00-context/how-the-orchard-works.md', `# How the Orchard Works

*Read this before deciding anything. It is the calibration.*

## The season

Bloom in the second week of May, give or take nine days. Thinning through June. First picking of
the early varieties — Lodi, Paulared — from the middle of August. The main harvest is six weeks
from the second week of September, and every argument the co-op has ever had happens inside those
six weeks.

## Who decides what

**The board decides money and membership.** Eleven votes, one per farm, and a tie means no.

**The packing house manager decides the schedule** during harvest, without consultation, because a
committee cannot run a line. Outside harvest the schedule is the board's.

**Nobody decides grading.** Grading is the CFIA standard and the standard is not a matter of
opinion, however strongly Ellis feels about it.

## Things that look like decisions and are not

- *"We should look into it."* — This is not an approval.
- *"I don't hate it."* — This is Ellis approving.
- Silence on a Tuesday is silence. Silence after a Friday board email is agreement.
`],

  // --- 01-internal ---------------------------------------------------------------------------
  ['01-internal/00-bridge/00-context/context.md', `# The Bridge

Where the co-op's shared work meets the member farms. Anything that has to cross that line gets
staged here first.
`],
  ['01-internal/00-bridge/01-department-inbox/note-from-hollis-farm.md', `# Note from Hollis Farm

Dropped off 3 April. Hollis wants the cold store allocation revisited before bloom, not after.
Their argument is that last year's allocation was set on the previous year's tonnage and they had
grown by a third. Hard to argue with. Goes to the board.
`],
  ['01-internal/00-bridge/01-department-inbox/scanned-invoice.md', `# Scanned invoice — Valley Crating

Three hundred and forty bins, delivered 11 March, invoiced 19 March. The invoice says 350. Someone
needs to walk the yard and count.
`],
  ['01-internal/00-bridge/03-agent-workspaces/packing-house/tasks/01-urgent/line-two-bearing.md',
    `# Line two — bearing noise

The elevator on line two has been making a noise since Thursday. Sounds like a bearing. It runs,
but it runs *louder*, and the last time something ran louder we lost a day and a half.

**Do this before harvest, not during.** A day in April is a day. A day in September is forty
thousand pounds.
`],
  ['01-internal/00-bridge/03-agent-workspaces/packing-house/tasks/02-next/replace-grading-lamps.md',
    `# Replace the grading lamps

The colour temperature has drifted on the west bank. Graders are compensating by eye, which works
right up until it doesn't and a pallet of 2s goes out as 1s.

Quoted: $1,840 for the full bank. Approved in principle, not yet scheduled.
`],
  ['01-internal/00-bridge/03-agent-workspaces/packing-house/tasks/04-done/repaint-floor-markings.md',
    `# Repaint the floor markings

Done, 22 February. Forklift lanes, pedestrian walkway, the bin staging squares. Two coats.
`],
  ['01-internal/00-bridge/03-agent-workspaces/packing-house/tasks/archive/2025-forklift-training.md',
    `# Forklift training, 2025

Six certified, two lapsed, one declined. Superseded by the 2026 schedule.
`],

  ['01-internal/food-safety/00-context/context.md', `# Food Safety

CanadaGAP certification, renewed annually. The audit is unannounced within a three-week window,
which in practice means the packing house is audit-ready from mid-August.
`],
  ['01-internal/food-safety/00-context/knowledgebase/index.md', `# Food Safety Knowledgebase

- [Water testing schedule](water-testing.md)
- [Traceability from bin to pallet](traceability.md)
- [What the auditor actually looks at](audit-reality.md)
`],
  ['01-internal/food-safety/00-context/knowledgebase/water-testing.md', `# Water testing

Well water, dump tank, and the final rinse. Three samples, quarterly, plus one within seven days
of the start of harvest.

| Source | Frequency | Threshold |
|--------|-----------|-----------|
| Well | Quarterly | < 1 CFU/100 mL generic E. coli |
| Dump tank | Weekly during harvest | Sanitizer 50–100 ppm free chlorine, pH 6.5–7.5 |
| Final rinse | Weekly during harvest | Potable |

The dump tank log is the one that gets missed, because it is the one that has to be filled in by
whoever is standing there at 6 a.m.
`],
  ['01-internal/food-safety/00-context/knowledgebase/traceability.md', `# Traceability from bin to pallet

Every bin carries a tag: farm, block, pick date. The tag travels to the dump tank and is recorded
against the run. The run is recorded against the pallet.

**The weak link is the dump tank.** Two farms' bins in one run and the pallet inherits both. That
is legal, and it is also why a recall would take out twice as much fruit as it needs to.
`],
  ['01-internal/food-safety/00-context/knowledgebase/audit-reality.md', `# What the auditor actually looks at

Not the binder. The binder is table stakes and they skim it.

They look at: the dump tank log (is it filled in *contemporaneously*, or in one handwriting on one
day?), the pest monitoring stations (are they where the map says?), and whether anyone on the
floor can answer "what do you do if you find glass?" without looking it up.

Two of the three are about whether the paperwork describes something that actually happens.
`],

  // --- 02-projects: the flagship, with a nested op and a round table ---------------------------
  ['02-projects/cold-store-expansion/00-context/context.md', `# Cold Store Expansion

The co-op has 40,000 bushels of controlled-atmosphere capacity and members produced 61,000 bushels
last year. The gap goes out the door in October at whatever October pays.

**This project is about closing that gap.** Not about whether to — the board voted in November.
About how big, where, and paid for how.
`],
  ['02-projects/cold-store-expansion/00-context/m-thread-cold-store-expansion.md',
    `# M-thread — Cold Store Expansion

*The running record. Newest at the bottom.*

## M1 — 12 November 2025

Board approved in principle. No number attached, which is going to be the whole problem.

## M2 — 8 January 2026

Three quotes requested. Two arrived. Maritime Refrigeration quoted $1.24M for 20,000 bushels of
CA; Cornerstone quoted $980K for 18,000 but their CA rooms are a licensed design and the licence
fee is not in the number.

## M3 — 2 February 2026

Ellis raised the obvious thing nobody had said out loud: **the packing line cannot feed 61,000
bushels through in six weeks regardless of where we put them.** Storage is not the constraint;
throughput is. This may be the wrong project.

## M4 — 19 February 2026

Ran the numbers. Ellis is half right. Line capacity is 3,400 bu/day at current staffing and the
harvest window is 30 working days — 102,000 bushels, so throughput is *not* binding on paper.
It binds in practice because the line does not run 30 days; it runs the days the fruit arrives,
and the fruit arrives in three surges.

**Reframed:** the expansion buys us the ability to hold a surge and run it flat.

## M5 — 4 March 2026

Round table opened to test the reframe before spending a million dollars on it. See \`03-discovery/RT1\`.

## M6 — 27 March 2026

RT1 came back with something we did not expect and it has changed the shape of the project. Short
version: the surge is not weather, it is **contractual** — six farms have the same pick-order
clause with the same broker and it fires on the same trigger. Renegotiating six clauses is a great
deal cheaper than a cold store.

**Not cancelled.** Reduced. See the RT1 record before reading anything above M6 as current.
`],
  ['02-projects/cold-store-expansion/01-inbox/maritime-quote-followup.md',
    `# Maritime Refrigeration — follow-up

They called. The quote holds until 30 April, then it is re-priced against steel. Nobody has told
them the project shrank.
`],
  ['02-projects/cold-store-expansion/01-inbox/note-on-provincial-grant.md',
    `# Provincial grant — possible

Agri-Food Innovation stream. Up to 35% of eligible capital, cap $400K. Application window opens
1 June. Eligibility is the question: "expansion of storage capacity" is listed, "renegotiating
your contracts so you don't need storage capacity" is emphatically not.
`],
  ['02-projects/cold-store-expansion/02-work/objectives/close-the-october-gap.md',
    `# Objective — Close the October gap

**21,000 bushels leave the co-op every October at spot price.** Spot in October averages $0.19/lb
against $0.31/lb for stored fruit sold in February.

At 40 lb/bushel that is 840,000 lb, and a $0.12 spread is **just over $100,000 a year**.

The objective is the hundred thousand. It is not the cold store — the cold store was one way to
get it, and after RT1 it looks like the expensive way.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/01-urgent/get-the-broker-contract.md',
    `# Get a copy of the broker contract

We are reasoning about a clause nobody in this office has read. Three farms have offered to share
theirs. Get all three and diff them — RT1's finding rests on them being identical and that is
currently a claim, not a fact.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/01-urgent/tell-maritime.md',
    `# Tell Maritime the project changed

Overdue and slightly awkward. They have done real work on a quote for something we may not build.
Call, do not email.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/02-next/model-the-reduced-build.md',
    `# Model the reduced build

If the clause renegotiation lands, what is the residual surge? Model 6,000 and 10,000 bushels of
added CA against the same $0.12 spread and see where the payback crosses ten years.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/02-next/grant-eligibility-question.md',
    `# Ask the province the eligibility question

Do not ask "are we eligible". Ask "is a 6,000-bushel CA addition eligible under the storage
stream" — a narrow question gets an answer, a broad one gets a phone call in September.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/03-back-burner/second-loading-dock.md',
    `# A second loading dock

Came up twice in RT1 and both times as an aside. Probably real, definitely not now.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/04-done/pull-five-years-of-tonnage.md',
    `# Pull five years of tonnage by farm

Done, 14 February. In \`03-shared-canvas/tonnage-2021-2025.md\`. Hollis has grown 34%, Bray has
shrunk 11%, everyone else is flat within noise.
`],
  ['02-projects/cold-store-expansion/02-work/tasks/unsorted-thought.md',
    `# Unsorted — insurance

Does a bigger CA room change the insurance? Nobody has asked. Not urgent, not filed anywhere yet.
`],
  ['02-projects/cold-store-expansion/03-shared-canvas/tonnage-2021-2025.md',
    `# Tonnage by farm, 2021–2025

Bushels, rounded to the nearest hundred.

| Farm | 2021 | 2022 | 2023 | 2024 | 2025 |
|------|-----:|-----:|-----:|-----:|-----:|
| Hollis | 8,200 | 8,900 | 9,400 | 10,600 | 11,000 |
| Bray | 7,100 | 6,900 | 6,800 | 6,400 | 6,300 |
| Kestrel | 6,500 | 6,600 | 6,400 | 6,700 | 6,600 |
| Nine Mile | 5,900 | 5,800 | 6,100 | 5,900 | 6,000 |
| Ardith | 4,800 | 5,000 | 4,900 | 5,100 | 5,000 |
| Others (6) | 25,300 | 25,600 | 25,900 | 26,100 | 26,100 |
| **Total** | **57,800** | **58,800** | **59,500** | **60,800** | **61,000** |

Two things fall out. The total is flat — the co-op is not growing, it is **reallocating**. And
Hollis alone accounts for every bushel of the increase, which is why their allocation complaint
is not really a complaint.
`],
  ['02-projects/cold-store-expansion/03-shared-canvas/open-questions.md',
    `# Open questions

1. Are the six broker clauses actually identical? *(RT1 rests on it — see the urgent task)*
2. Does the province's storage stream cover a smaller build?
3. What does the packing house manager think? **Nobody has asked her.** She was not in RT1 and
   she is the only person who has watched all three surges arrive.
4. Insurance.
`],
  ['02-projects/cold-store-expansion/archive/original-1.24m-proposal.md',
    `# Original proposal — $1.24M, 20,000 bushels

Superseded by M6. Kept because the cost breakdown in section 3 is still the best one we have and
the reduced build will reuse most of it.
`],

  // ... the nested op, three levels deep
  ['02-projects/cold-store-expansion/02-work/projects/op-broker-renegotiation/00-context/context.md',
    `# Op — Broker Renegotiation

Six farms, one broker, one clause. If the clause moves, the surge moves, and a million dollars of
concrete stops being necessary.

**This is an op, not a project:** it has a target, a deadline that is not ours to move (the clause
renews 1 July), and it either lands or it doesn't.
`],
  ['02-projects/cold-store-expansion/02-work/projects/op-broker-renegotiation/00-context/m-thread-broker-renegotiation.md',
    `# M-thread — Broker Renegotiation

## M1 — 30 March 2026

Opened out of RT1's finding. Six farms have the same pick-order clause with Tidewater Produce and
it fires on the same trigger: first delivery within 72 hours of the broker's call.

## M2 — 2 April 2026

Two of the six have already said they will not move. Both sell more than half their crop through
Tidewater and the clause is what buys them the volume commitment. **Fair.**

Four of six may still be enough — the surge is a threshold effect, not a linear one.

## M3 — 6 April 2026

Modelled it. Four of six flattens the peak from 4,900 bu/day to 3,600. Line capacity is 3,400.
*So close it hurts.*
`],
  ['02-projects/cold-store-expansion/02-work/projects/op-broker-renegotiation/02-work/tasks/01-urgent/talk-to-kestrel.md',
    `# Talk to Kestrel

Kestrel is the fifth farm and the swing. They do not depend on Tidewater volume the way Bray and
Nine Mile do; they signed the same clause because it was the paper in front of them.

If Kestrel moves, the peak drops under line capacity and the op has landed.
`],
  ['02-projects/cold-store-expansion/02-work/projects/op-broker-renegotiation/02-work/tasks/02-next/draft-the-alternative-clause.md',
    `# Draft the alternative clause

Not "remove the pick-order clause" — Tidewater will not sign that and it is not what we need.
**Stagger the trigger.** Same 72 hours, different anchor dates per farm.
`],
  ['02-projects/cold-store-expansion/02-work/projects/op-broker-renegotiation/03-shared-canvas/clause-comparison.md',
    `# Clause comparison — the six

*Provisional. Only three contracts have actually been read.*

| Farm | Read? | Trigger | Window |
|------|-------|---------|--------|
| Hollis | Yes | Broker's call | 72 h |
| Bray | Yes | Broker's call | 72 h |
| Kestrel | Yes | Broker's call | 72 h |
| Nine Mile | No | *assumed* | *assumed* |
| Ardith | No | *assumed* | *assumed* |
| Two Rivers | No | *assumed* | *assumed* |

**Three of six is not "identical".** The urgent task exists to close this.
`],

  // ... a round table under the flagship project
  ['02-projects/cold-store-expansion/03-discovery/RT1/00-context/m-thread-RT1.md',
    `# RT1 — Is storage the actual constraint?

## The question on the table

The board approved a cold store. Ellis says the constraint is throughput, not storage. Both cannot
be the thing we spend a million dollars on.

## M1 — 4 March 2026

Opened. Four seats: packing (empty — see below), finance, two member farms.

**The packing seat was never filled** and this is a defect in the round table, recorded here rather
than smoothed over. The one person who has watched every surge arrive was not asked.

## M2 — 11 March 2026

Finance brought the tonnage curve and it did the work. The annual total is flat. The *daily* curve
has three spikes, and the spikes are not weather-shaped — weather is a bell, these are cliffs.

## M3 — 18 March 2026

Kestrel's delegate recognised the cliff. It is the Tidewater call. Six farms, one phone call,
72 hours.

**This is the finding.** The surge is contractual.

## M4 — 27 March 2026

Closed. Recommendation: open an op on the clause before committing capital. Board agreed 9–2.
`],
  ['02-projects/cold-store-expansion/03-discovery/RT1/02-shared-canvas/the-daily-curve.md',
    `# The daily intake curve

Bushels received per working day, 2025 harvest, week 3 onward.

\`\`\`
 5000 |            ▇                    ▇
 4000 |            ▇         ▇          ▇
 3000 |    ▃  ▄    ▇    ▄    ▇     ▄    ▇    ▃
 2000 |  ▂ ▃  ▄ ▃  ▇  ▃ ▄ ▂  ▇  ▃  ▄ ▂  ▇ ▃  ▃
 1000 |  ▂ ▃  ▄ ▃  ▇  ▃ ▄ ▂  ▇  ▃  ▄ ▂  ▇ ▃  ▃
      +--------------------------------------------
        Sep 8      Sep 15    Sep 22     Sep 29
\`\`\`

Line capacity is the 3,400 mark. Three days over it, and on those three days fruit sits in the
yard warming up.

Weather does not do this. **A phone call does this.**
`],
  ['02-projects/cold-store-expansion/03-discovery/RT1/02-shared-canvas/what-we-got-wrong.md',
    `# What RT1 got wrong

Written at close, deliberately, because a round table that only records its finding is a round
table that will make the same mistake again.

1. **The packing seat was empty for all four sessions.** The finding is probably right and it was
   found without the one person best placed to have known it on day one.
2. **We modelled 2025 only.** One harvest. If 2024 does not show the same cliffs the finding is
   a coincidence with a good story attached.
3. **Nobody costed the renegotiation.** "Cheaper than a cold store" is true of almost everything.
`],
  ['02-projects/cold-store-expansion/03-discovery/RT1/chatroom.md',
    `# Chatroom — RT1

---

*Entries below. Format: \`## M1 -- Author Name\`. Append-only.*

## M1 -- Ellis

I'll say it again: we are about to build a warehouse because we can't answer the phone.

## M2 -- Finance

That's unfair. We're about to build a warehouse because the board voted to.

## M3 -- Ellis

Those are the same sentence.

## M4 -- Kestrel

Hang on. Say the 72 hours thing again.

## M5 -- Ellis

Tidewater calls, and you have three days to deliver or you're off the pick order.

## M6 -- Kestrel

We all have that clause.

## M7 -- Finance

...all of you?

## M8 -- Kestrel

All of us. Same paper. I think Hollis negotiated it in '19 and the rest of us signed
the same one because it was the one that existed.

## M9 -- Finance

Then that's the cliff. That's not weather, that's a *contract*.

## M10 -- Ellis

That's what I've been —

## M11 -- Finance

Yes. Yes, all right.
`],

  // --- a second project, thin on purpose ------------------------------------------------------
  ['02-projects/cider-line/00-context/context.md', `# Cider Line

The perennial. Comes up every February, dies every March. Documented here so that next February
somebody can read why it died the last four times instead of relitigating it.
`],
  ['02-projects/cider-line/00-context/m-thread-cider-line.md', `# M-thread — Cider Line

## M1 — 9 February 2026

Raised again by Two Rivers. Same proposal as 2023: press the 2s and the culls, sell into the craft
market.

## M2 — 16 February 2026

Same objection as 2023, 2024 and 2025: **the 2s are already sold.** They go to Bayline Fruit for
processing at a price that is unexciting and guaranteed. Cider is more per litre and less per
hour, and it needs capital we have committed to the cold store.

## M3 — 3 March 2026

Two Rivers accepted the objection but asked a better question this time: *what would have to be
true?* Answer: the Bayline Fruit contract would have to lapse, or a member would have to build the
press on their own land and buy the 2s at market.

That second one is live. Two Rivers may do it themselves.
`],
  ['02-projects/cider-line/01-inbox/craft-market-numbers.md', `# Craft cider market — numbers

Dropped in by Two Rivers, unverified. NS craft cider grew 14% by volume 2024→2025. Average
wholesale $4.20/L. A tonne of 2s yields roughly 600 L.
`],
  ['02-projects/cider-line/archive/2023-proposal.md', `# 2023 proposal

Died on the Bayline Fruit contract. See the M-thread — it dies on that every year.
`],
  ['02-projects/cider-line/archive/2024-proposal.md', `# 2024 proposal

Identical to 2023 with a different cover page.
`],

  // --- inboxes at every level, in the spellings the real tree uses ----------------------------
  ['99-inbox-main/bin-tag-printer-quote.md', `# Bin tag printer — quote

$3,100 for the Zebra unit, $890/yr for ribbon and labels. The current printer is nine years old
and jams on humid days, which during harvest is all of them.
`],
  ['99-inbox-main/email-from-cfia.md', `# Email from CFIA

Routine. Confirming the packing house registration number is unchanged for 2026. No action.
`],
  ['99-inbox-main/hollis-wants-a-meeting.md', `# Hollis wants a meeting

About the allocation. See \`01-internal/00-bridge/01-department-inbox/note-from-hollis-farm.md\` —
this is the same thing arriving twice, which is usually a sign it is real.
`],
  ['98-random-discovery/why-do-we-grade-on-the-line.md', `# Why do we grade on the line?

Genuinely unclear. Every other packing house in the valley grades at intake. We grade after the
dump tank, which means we wash fruit we then throw away.

Nowhere to file this yet. It might be nothing, it might be a day of throughput.
`],

  // --- pipelines and research ------------------------------------------------------------------
  ['03-execution-environments/harvest-intake-pipeline/00-context/context.md',
    `# Harvest Intake Pipeline

Bin arrives → tag scanned → weighed → dump tank → graded → packed → palletised → cold store.

Eight steps, and the record only exists at three of them.
`],
  ['03-execution-environments/harvest-intake-pipeline/02-work/tasks/02-next/close-the-record-gap.md',
    `# Close the record gap

Five of eight steps produce no record. Traceability survives because the *run* is recorded, but a
run is an hour and an hour is two farms.
`],
  ['04-experiments-and-research/reflective-mulch-trial/00-context/context.md',
    `# Reflective mulch trial

Two blocks at Ardith, Honeycrisp, third leaf. Extenday on one, bare ground on the other.
Measuring colour development at harvest.
`],
  ['04-experiments-and-research/reflective-mulch-trial/03-shared-canvas/2025-results.md',
    `# 2025 results

Colour on the treated block ran roughly 8 points higher on the CTIFL chart, which moved about 12%
of the crop from Grade 2 to Grade 1.

**Confounded.** The treated block is also the one with the newer trellis. One season, two blocks,
one variable that is actually two. Repeat before believing.
`],

  // --- a board, and the shapes P14 has to get right ----------------------------------------------
  //
  // `2024-board-minutes.md` above already sits in this tree and is NOT a board: it is a file, and
  // the archive excludes it twice over. It was here before P14 and is left exactly as it was — a
  // free negative case is worth more than one written to pass.
  //
  // The board below carries every case the grammar has to separate, so the e2e drives real shapes
  // rather than a folder made of two happy files.

  ['02-projects/orchard-co-op/board-cold-store/01-doing/compressor-quote.md',
    `# Compressor quote

Three quotes in, the middle one is the only supplier who has done a store this size before.
`],
  ['02-projects/orchard-co-op/board-cold-store/01-doing/insulation-spec.md',
    `# Insulation spec

100mm panel throughout. The corner detail is the part nobody costs properly.
`],
  ['02-projects/orchard-co-op/board-cold-store/02-done/site-visit.md',
    `# Site visit

Floor is level to within 8mm across the span, which is inside tolerance.
`],

  // Loose in the board's own folder — the Uncategorized case, and the one the operator has not ruled on.
  ['02-projects/orchard-co-op/board-cold-store/dropped-in-by-an-agent.md',
    `# Dropped in by an agent

Written straight into the board folder rather than into a column, which is what agents will do.
`],

  // A subfolder inside a column: NOT a card, NOT a column. "No nested cards" reaching disk.
  ['02-projects/orchard-co-op/board-cold-store/01-doing/attachments/panel-datasheet.md',
    `# Panel datasheet

Deeper than a column, so the board does not draw it. Files still shows it.
`],

  // A second board elsewhere, so the home list has to sort and disambiguate rather than show one row.
  ['02-projects/reflective-mulch/board-tuesday-drops/inbox/first-pass.md',
    `# First pass

A second board, in a different project, so the list is a list.
`],

  // An ARCHIVED board. Must not appear in Boards at all — the only retire path, since nothing deletes.
  ['02-projects/orchard-co-op/archive/board-old-launch/done/shipped.md',
    `# Shipped

This board is archived. It must not appear in the Boards tab.
`],

  // --- root-level archive -----------------------------------------------------------------------
  ['archive/2024-board-minutes.md', `# Board minutes, 2024

Twelve meetings. The cold store first appears in the September minutes as an "other business" item.
`],
]

// ---------------------------------------------------------------------------------------------
// 2 · THE BULK — deterministic, and sized against the real tree
// ---------------------------------------------------------------------------------------------

/** Mulberry32. Deterministic by construction — no clock, no `Math.random`. */
function seeded(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const NOUNS = [
  'allocation', 'bin count', 'bloom window', 'brix reading', 'cold chain', 'cull rate',
  'dump tank', 'grading standard', 'harvest window', 'intake curve', 'labour draw',
  'packing schedule', 'pick order', 'pollination', 'pressure test', 'rootstock', 'scab pressure',
  'spot price', 'storage loss', 'thinning pass', 'trellis spacing', 'water sample',
]
const VERBS = [
  'held flat against', 'came in under', 'ran ahead of', 'was revised after', 'now depends on',
  'contradicts', 'was measured against', 'stalls on', 'was deferred pending', 'confirms',
]
const QUALIFIERS = [
  'on one season of data', 'against the five-year mean', 'before the board voted',
  'without the packing house in the room', 'on Ardith and Kestrel only', 'in the 2025 numbers',
  'assuming the clause holds', 'at current staffing', 'if the weather behaves',
]
const FARMS = ['Hollis', 'Bray', 'Kestrel', 'Nine Mile', 'Ardith', 'Two Rivers', 'Larkspur']
const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
]

const pick = <T,>(rng: () => number, list: readonly T[]): T =>
  list[Math.floor(rng() * list.length)] as T

function sentence(rng: () => number): string {
  const shape = rng()
  if (shape < 0.25) {
    return `${pick(rng, FARMS)} reports the ${pick(rng, NOUNS)} ${pick(rng, VERBS)} the ${pick(rng, NOUNS)}, ${pick(rng, QUALIFIERS)}.`
  }
  if (shape < 0.5) {
    return `The ${pick(rng, NOUNS)} ${pick(rng, VERBS)} last year's figure — ${Math.floor(rng() * 900 + 100)} against ${Math.floor(rng() * 900 + 100)}.`
  }
  if (shape < 0.7) {
    return `Nobody has checked whether the ${pick(rng, NOUNS)} still holds ${pick(rng, QUALIFIERS)}.`
  }
  if (shape < 0.85) {
    return `Raised ${Math.floor(rng() * 27 + 1)} ${pick(rng, MONTHS)}; unresolved.`
  }
  return `**${pick(rng, FARMS)} disagrees**, and the disagreement is about the ${pick(rng, NOUNS)} rather than the number.`
}

function paragraph(rng: () => number): string {
  const n = 2 + Math.floor(rng() * 4)
  return Array.from({ length: n }, () => sentence(rng)).join(' ')
}

/**
 * THE CONSTRUCT CENSUS, and why these proportions and not others.
 *
 * Measured on the real tree on 2026-08-08 — counts of files containing each construct, out of 4,619
 * markdown files. Reproduced here because **the fake soil is only a stand-in for the real one to the
 * extent it carries the same things**, and Phase 5 needs it to stand in for a corpus of *damage*:
 * the old editor's destruction was per-construct, and a corpus missing a construct cannot detect
 * the loss of it.
 *
 * The first version of this generator carried tables, fences, blockquotes and lists — and **zero
 * frontmatter, zero wikilinks, zero task boxes, zero footnotes, zero images, one HTML tag.** Those
 * absences line up almost exactly with the destructive categories the old harness counts
 * (`frontmatter_destroyed`, `wikilinks_escaped`, `taskboxes_lost`, `footnotes_escaped`,
 * `images_lost`, `html_tags_lost`, `html_comments_lost`, `entities_introduced`). The mock tree was
 * built for *filesystem* hazards and is excellent at those; it was blind to markdown ones.
 *
 * **Frontmatter is the one that matters most:** 49% of the real tree carries it, and the old editor
 * silently flattened it in 944 files — a `---` block rendered as a thematic break plus a setext
 * heading. A damage corpus without frontmatter cannot see the headline defect.
 */
const CONSTRUCT_SHARE = {
  frontmatter: 0.49,   // 2,282 / 4,619
  codeFence: 0.16,     // 751
  blockquote: 0.14,    // 663
  table: 0.13,         // 616
  htmlTag: 0.10,       // 464
  wikilink: 0.054,     // 250
  taskBox: 0.031,      // 141
  /**
   * **THE RARE TAIL IS DELIBERATELY OVER-REPRESENTED, and that is not a fidelity failure.**
   *
   * Faithful proportions put images in 5 files and entities in 6, out of ~1,400 — the real tree's
   * own rates. That is representative and useless: a corpus with five instances of a construct
   * cannot measure damage to it, because five is inside the noise of anything that goes wrong for
   * an unrelated reason.
   *
   * Two different goals are in tension and only one of them is proportionality. For the common
   * constructs the corpus must look like the tree, so a percentage means something. For the rare
   * tail it must carry **enough instances to measure**, and the tree's own rate is the wrong
   * target. These four are raised to land around 15–20 files each; their real rates stay in the
   * comments so the divergence is visible rather than looking like a mistake.
   */
  htmlComment: 0.014,  // 66 real (1.4%) — already sufficient at this rate
  image: 0.012,        // 24 real (0.5%) — raised for sufficiency
  entity: 0.012,       // 20 real (0.4%) — raised
  footnote: 0.012,     // 19 real (0.4%) — raised
} as const

/** A generated document. Shapes mirror the archetypes the real tree is full of. */
function document(rng: () => number, title: string): string {
  const lines: string[] = []

  /**
   * Frontmatter first, because it must be the first bytes of the file or it is not frontmatter —
   * and "renders as a thematic break plus a setext heading instead" is the exact bug this exists
   * to catch.
   */
  if (rng() < CONSTRUCT_SHARE.frontmatter) {
    lines.push('---')
    lines.push(`title: ${title}`)
    lines.push(`status: ${pick(rng, ['draft', 'active', 'archived', 'blocked'])}`)
    if (rng() < 0.4) lines.push(`tags: [${pick(rng, NOUNS)}, ${pick(rng, NOUNS)}]`)
    if (rng() < 0.3) lines.push(`updated: 2026-0${1 + Math.floor(rng() * 8)}-1${Math.floor(rng() * 9)}`)
    lines.push('---', '')
  }

  lines.push(`# ${title}`, '')
  const sections = 2 + Math.floor(rng() * 4)

  // Drawn once per document — see the note in the section loop for why this is not per section.
  const carries = {
    table: rng() < CONSTRUCT_SHARE.table,
    codeFence: rng() < CONSTRUCT_SHARE.codeFence,
    blockquote: rng() < CONSTRUCT_SHARE.blockquote,
    htmlTag: rng() < CONSTRUCT_SHARE.htmlTag,
    wikilink: rng() < CONSTRUCT_SHARE.wikilink,
    taskBox: rng() < CONSTRUCT_SHARE.taskBox,
    htmlComment: rng() < CONSTRUCT_SHARE.htmlComment,
    image: rng() < CONSTRUCT_SHARE.image,
    entity: rng() < CONSTRUCT_SHARE.entity,
    footnote: rng() < CONSTRUCT_SHARE.footnote,
  }
  const inSection = (): number => Math.floor(rng() * sections)
  const tableSection = inSection()
  const fenceSection = inSection()
  const quoteSection = inSection()
  const taskSection = inSection()
  const linkSection = inSection()
  const htmlSection = inSection()

  for (let s = 0; s < sections; s += 1) {
    lines.push(`## ${pick(rng, NOUNS).replace(/^./, c => c.toUpperCase())}`, '')
    lines.push(paragraph(rng), '')

    /**
     * **Decided per document, not per section.** The census counts *files* containing a construct,
     * so drawing per section would multiply each share by the section count and put tables in a
     * third of the tree. Each construct is drawn once above and placed in whichever section comes
     * up, which is what makes the generated distribution match the measured one.
     */
    if (carries.table && s === tableSection) {
      lines.push('| Farm | Bushels | Note |', '|------|--------:|------|')
      lines.push(...Array.from({ length: 3 + Math.floor(rng() * 4) },
        () => `| ${pick(rng, FARMS)} | ${Math.floor(rng() * 9000 + 500)} | ${pick(rng, QUALIFIERS)} |`))
      lines.push('')
    }
    if (carries.codeFence && s === fenceSection) {
      lines.push('```', `intake  ${Math.floor(rng() * 5000)} bu/day`,
        'line    3400 bu/day', `delta   ${Math.floor(rng() * 1600) - 800}`, '```', '')
    }
    if (carries.blockquote && s === quoteSection) lines.push(`> ${sentence(rng)}`, '')

    if (carries.taskBox && s === taskSection) {
      // Unchecked and checked both — the old editor lost the box, not the line, so a corpus with
      // only one state cannot tell "unchecked became checked" from "the box survived".
      lines.push(`- [ ] ${sentence(rng)}`, `- [x] ${sentence(rng)}`, '')
    }
    if (carries.wikilink && s === linkSection) {
      lines.push(`See [[${pick(rng, BULK_PROJECTS)}]] and [the note](../${pick(rng, NOUNS)}.md).`, '')
    }
    if (carries.htmlTag && s === htmlSection) {
      lines.push(`<sub>${pick(rng, QUALIFIERS)}</sub> — recorded <b>before</b> the vote.`, '')
    }
    if (carries.htmlComment && s === htmlSection) {
      lines.push(`<!-- carried from the ${pick(rng, MONTHS)} minutes; do not reflow -->`, '')
    }
    if (carries.image && s === linkSection) {
      lines.push(`![${pick(rng, NOUNS)} yield](../assets/${pick(rng, NOUNS)}.png)`, '')
    }
    if (carries.entity && s === htmlSection) {
      lines.push(`Bins were 40&nbsp;kg &amp; stacked three high &mdash; see below.`, '')
    }

    if (rng() < 0.22) {
      lines.push(...Array.from({ length: 2 + Math.floor(rng() * 4) },
        () => `- ${sentence(rng)}`), '')
    }
  }

  if (carries.footnote) {
    // Definitions go at the end, which is where they are in the real tree and where a reflowing
    // editor is most likely to escape the `[^n]` marker.
    lines.push(`The ${pick(rng, NOUNS)} was disputed[^1].`, '', `[^1]: ${sentence(rng)}`, '')
  }

  return lines.join('\n')
}

/** Where the bulk goes, and how much of it. Roughly the real tree's distribution. */
const BULK_PROJECTS = [
  'orchard-renewal', 'labour-and-housing', 'spray-program', 'equipment-replacement',
  'membership-review', 'export-certification', 'packing-house-layout', 'variety-transition',
  'irrigation-study', 'insurance-renewal', 'brand-and-market', 'succession-planning',
  'frost-protection', 'bin-logistics', 'pollination-contracts', 'grading-standards',
  'cold-chain-audit', 'roadside-retail', 'orchard-floor-management', 'crop-insurance-claim',
  'water-rights',
]

const LANES = ['01-urgent', '02-next', '03-back-burner', '04-done']

/**
 * Generates the bulk. Deterministic given `seed`.
 *
 * Target is the real tree's shape rather than a round number: ~1,500 documents across ~1,800
 * directories, reaching 16 levels at the deepest point.
 */
export function bulkFiles(seed = 20260808): PlainFile[] {
  const rng = seeded(seed)
  const out: PlainFile[] = []
  /**
   * A conversation in the soil's own format — `00-context/protocols/chatroom-protocol.md`:
   *
   * > *"Must be `##` (H2) — not `###` or `#`. Must use `--` (double hyphen) — not an em-dash or an
   * > en-dash. M-number comes FIRST, then `--`, then author name."*
   *
   * The third message deliberately contains a `##` heading of its own, because the protocol
   * promises that is safe: *"content pasted into a message body can use `##` headers freely — the
   * parser regex is strict enough to ignore them."* A fixture that never exercises the promise
   * cannot catch the day it stops being true.
   */
  const chatroom = (name: string): string => [
    `# Chatroom — ${name}`,
    '',
    '---',
    '',
    '*Entries below. Format: `## M1 -- Author Name`. Append-only.*',
    '',
    '## M1 -- Ada',
    '',
    'Opening the round table. The question is whether the numbers hold.',
    '',
    '## M2 -- Ellis',
    '',
    'They hold for the first season and then stop. Worth saying out loud before we go further.',
    '',
    '## M3 -- Ada',
    '',
    'Pasting the working below.',
    '',
    '## Working',
    '',
    'A heading inside a message body, which the protocol says is safe.',
    '',
  ].join('\n')

  const add = (path: string, title: string): void => { out.push([path, document(rng, title)]) }

  for (const [i, project] of BULK_PROJECTS.entries()) {
    const base = `02-projects/${project}`
    add(`${base}/00-context/context.md`, `${project.replace(/-/g, ' ')} — context`)
    add(`${base}/00-context/m-thread-${project}.md`, `M-thread — ${project.replace(/-/g, ' ')}`)

    for (let k = 0; k < 3 + (i % 4); k += 1) {
      add(`${base}/01-inbox/note-${k + 1}.md`, `Inbox note ${k + 1}`)
    }
    for (const lane of LANES) {
      for (let k = 0; k < 2 + Math.floor(rng() * 6); k += 1) {
        add(`${base}/02-work/tasks/${lane}/card-${k + 1}.md`, `Card ${k + 1} — ${lane.slice(3)}`)
      }
    }
    for (let k = 0; k < 1 + (i % 3); k += 1) {
      add(`${base}/02-work/objectives/objective-${k + 1}.md`, `Objective ${k + 1}`)
    }
    for (let k = 0; k < 2 + Math.floor(rng() * 5); k += 1) {
      add(`${base}/03-shared-canvas/report-${k + 1}.md`, `Report ${k + 1}`)
    }
    for (let k = 0; k < 1 + Math.floor(rng() * 5); k += 1) {
      add(`${base}/archive/retired-${k + 1}.md`, `Retired ${k + 1}`)
    }

    // Nested ops, and inside two of them a round table — the real tree's deepest shape.
    for (let o = 0; o < 1 + (i % 3); o += 1) {
      const op = `${base}/02-work/projects/op-${project}-${o + 1}`
      add(`${op}/00-context/context.md`, `Op ${o + 1} — context`)
      add(`${op}/00-context/m-thread-op-${o + 1}.md`, `M-thread — op ${o + 1}`)
      for (const lane of LANES.slice(0, 3)) {
        for (let k = 0; k < 1 + Math.floor(rng() * 4); k += 1) {
          add(`${op}/02-work/tasks/${lane}/card-${k + 1}.md`, `Op card ${k + 1}`)
        }
      }
      for (let k = 0; k < 1 + Math.floor(rng() * 3); k += 1) {
        add(`${op}/03-shared-canvas/canvas-${k + 1}.md`, `Canvas ${k + 1}`)
      }
      if (o === 0) {
        for (let r = 1; r <= 1 + (i % 3); r += 1) {
          const rt = `${op}/03-discovery/RT${r}`
          add(`${rt}/00-context/m-thread-RT${r}.md`, `RT${r} record`)
          /**
           * **A chatroom in the format the soil actually writes**, not a generic document.
           *
           * The generated rooms were `document(...)` stubs and the one hand-written room used
           * `**Name** — text`, so **not a single chatroom in the mock matched
           * `00-context/protocols/chatroom-protocol.md`** — the format §14 parses. A visual check
           * of the conversation surface against this tree therefore proved nothing: every room
           * rendered as one undifferentiated block, which is exactly what a *broken* parser would
           * also produce.
           *
           * The mock's whole purpose is to be the same shape as the real thing. A fixture that is
           * the wrong shape is worse than no fixture, because it looks like evidence.
           */
          out.push([`${rt}/chatroom.md`, chatroom(rt.split('/').pop() ?? 'RT')])
          for (let k = 0; k < 1 + Math.floor(rng() * 4); k += 1) {
            add(`${rt}/02-shared-canvas/finding-${k + 1}.md`, `Finding ${k + 1}`)
          }
          // One discovery unit per RT1, which is where 16 levels comes from.
          if (r === 1) {
            const d = `${rt}/03-discovery/discovery-${project}/02-shared-canvas/deep`
            add(`${d}/vision.md`, 'Vision')
            add(`${d}/notes/session-notes.md`, 'Session notes')
          }
        }
      }
    }
  }

  // Departments, the bridge, and the standing knowledgebase.
  for (const dept of ['food-safety', 'finance', 'membership', 'packing', 'orchard-ops']) {
    const base = `01-internal/${dept}`
    add(`${base}/00-context/context.md`, `${dept} — context`)
    for (let k = 0; k < 4 + Math.floor(rng() * 8); k += 1) {
      add(`${base}/00-context/knowledgebase/entry-${k + 1}.md`, `Knowledgebase entry ${k + 1}`)
    }
    for (let k = 0; k < 2 + Math.floor(rng() * 5); k += 1) {
      add(`${base}/01-inbox/item-${k + 1}.md`, `Inbox item ${k + 1}`)
    }
    for (let k = 0; k < 2 + Math.floor(rng() * 6); k += 1) {
      add(`${base}/03-shared-canvas/standard-${k + 1}.md`, `Standard ${k + 1}`)
    }
    for (let k = 0; k < 2 + Math.floor(rng() * 8); k += 1) {
      add(`${base}/archive/superseded-${k + 1}.md`, `Superseded ${k + 1}`)
    }
  }

  for (let k = 0; k < 40; k += 1) add(`99-inbox-main/dropped-${k + 1}.md`, `Dropped item ${k + 1}`)
  for (let k = 0; k < 24; k += 1) add(`archive/season-note-${k + 1}.md`, `Season note ${k + 1}`)

  return out
}

/**
 * Directories that exist and hold nothing.
 *
 * **Added after measuring the first build.** It produced 1,535 files — near enough the real
 * tree's 1,567 — in 979 directories against the real 1,822. Files were right and *shape* was not:
 * the real soil runs at roughly 0.86 files per directory because a scaffolded project creates its
 * whole folder set whether or not anything is put in them, and template trees are almost entirely
 * empty folders. A fixture at 1.57 files per directory under-exercises the walk by about half,
 * and the walk is the thing that has to survive 1,800 of these.
 *
 * So these are not padding. They are the folders a template copy leaves behind, which is also
 * why an empty lane has to render as nothing rather than as a broken card.
 */
export function bulkDirectories(): string[] {
  const out: string[] = []

  for (const [i, project] of BULK_PROJECTS.entries()) {
    const base = `02-projects/${project}`
    out.push(
      `${base}/00-context/knowledgebase`,
      `${base}/00-context/conventions`,
      `${base}/01-inbox/reference`,
      `${base}/02-work/tasks/05-blocked`,
      `${base}/03-shared-canvas/attachments`,
      `${base}/archive/2024`,
      `${base}/archive/2025`,
    )
    for (let o = 0; o < 1 + (i % 3); o += 1) {
      const op = `${base}/02-work/projects/op-${project}-${o + 1}`
      out.push(
        `${op}/01-inbox`,
        `${op}/02-work/objectives`,
        `${op}/03-shared-canvas/attachments`,
        `${op}/archive`,
      )
      if (o === 0) {
        for (let r = 1; r <= 1 + (i % 3); r += 1) {
          out.push(`${op}/03-discovery/RT${r}/01-inbox`, `${op}/03-discovery/RT${r}/archive`)
        }
      }
    }
  }

  for (const dept of ['food-safety', 'finance', 'membership', 'packing', 'orchard-ops']) {
    out.push(
      `01-internal/${dept}/01-inbox/reference`,
      `01-internal/${dept}/02-department-workspace`,
      `01-internal/${dept}/03-shared-canvas/attachments`,
      `01-internal/${dept}/archive/superseded`,
    )
  }

  // The template trees — in the real soil these are almost entirely empty folders, and they are
  // the reason a naive "a directory with no markdown in it is not real" rule goes wrong.
  const SHAPES: Record<string, readonly string[]> = {
    'project-template': ['00-context', '01-inbox', '02-work/objectives', '02-work/projects',
      '02-work/tasks/01-urgent', '02-work/tasks/02-next', '02-work/tasks/03-back-burner',
      '02-work/tasks/04-done', '03-shared-canvas', 'archive'],
    'op-template': ['00-context', '01-inbox', '02-work/tasks', '03-discovery',
      '03-shared-canvas', 'archive'],
    'rt-template': ['00-context', '01-inbox', '02-shared-canvas', 'archive'],
    'discovery-mode-template': ['00-context', '01-inbox', '02-shared-canvas'],
  }
  for (const [name, shape] of Object.entries(SHAPES)) {
    for (const leaf of shape) out.push(`00-context/templates/work-templates/${name}/${leaf}`)
  }

  return out
}

// ---------------------------------------------------------------------------------------------
// 3 · THE HAZARDS — `zz-hazards/`, one folder per way a filesystem misbehaves
// ---------------------------------------------------------------------------------------------

const H = 'zz-hazards'
/** The deliberately hostile content, kept in its own folder under the hazards. */
const M = 'zz-hazards/malicious'

/**
 * A 249-byte basename: long, but legal — NAME_MAX is 255 bytes on this volume.
 *
 * **Measured 2026-08-08:** this name is accepted; the same name plus a conflict suffix is 279
 * bytes and the open fails `ENAMETOOLONG`. So the file is editable and its *rescue* is not, which
 * is precisely why §13.5 pre-validates the generated name in bytes rather than discovering the
 * limit at the open.
 */
const LONG_NAME = `${'long-'.repeat(49)}x.md` // 5*49 + 4 = 249 bytes

/**
 * The two Unicode forms, built from code points.
 *
 * Written as literals these are a trap that has already been sprung once in this build: an editor
 * or a file-writing tool normalizes both sides and the test then compares two byte-identical
 * strings while claiming to compare two forms. Code points cannot be normalized in transit.
 */
const E_NFC = String.fromCodePoint(0x00e9) // é
const E_NFD = String.fromCodePoint(0x0065, 0x0301) // e + U+0301 combining acute
const NFC_NAME = `r${E_NFC}sum${E_NFC}-nfc.md`
const NFD_NAME = `r${E_NFD}sum${E_NFD}-nfd.md`

/** The plain-text hazards. Nothing here needs anything beyond `writeFile`. */
export const HAZARD_FILES: readonly PlainFile[] = [
  [`${H}/README.md`, `# Hazards

Each folder here is a way the filesystem is allowed to behave that a naive reader assumes it
never will. They are in the mock tree on purpose. **The app is expected to handle every one of
them visibly** — refuse with a reason, or cope — and never to fail silently.

| Folder | What breaks if it is mishandled |
|--------|---------------------------------|
| \`unicode-names/\` | Filenames stop matching themselves; a rename creates a duplicate |
| \`awkward-names/\` | A name is mangled into another file's name, or into nothing |
| \`content-edges/\` | Bytes are "fixed" on save; a file gets shorter than it was |
| \`links/\` | A write travels through a link and lands outside the tree |
| \`permissions/\` | A save reports success against a file it could not write |
| \`already-conflicted/\` | The rescue file is treated as ordinary content |
| \`ignored/\` | Fifty thousand irrelevant files get indexed |
| \`not-markdown/\` | Something that is not a document is opened as one |
| \`deep/\` | A path grows past the limit during a copy and truncates |
`],

  // --- unicode ---------------------------------------------------------------------------------
  [`${H}/unicode-names/日本語のノート.md`, `# 日本語のノート

Non-Latin filename. The old slugifier mapped this to the empty string and produced a file called
\`.md\` — hidden by the dot rule and lost at creation.
`],
  [`${H}/unicode-names/notes-with-emoji-\u{1F331}.md`, `# Notes with an emoji

The 🌱 in this filename is outside the Basic Multilingual Plane. Anything counting "characters"
instead of code points or bytes will get its length wrong.
`],
  [`${H}/unicode-names/${NFD_NAME}`, `# resume (decomposed)

The accents in this filename are **combining marks** — \`e\` followed by U+0301. Its sibling in
this folder uses the single precomposed character instead. They look identical on screen and are
different byte sequences.

**Measured on this volume, 2026-08-08.** APFS is normalization-*insensitive* and
form-*preserving*, which is the combination that catches people:

- Creating the decomposed name and then writing to the composed name **found the same file and
  overwrote it.** One directory entry afterwards, not two.
- \`readdir\` returned the form the file was **first created with** — here, decomposed.
- Opening by either form works.

So a filename the app holds as a string can be a form the filesystem will never hand back.
Comparing two names as raw strings says "different file" where the filesystem says "same file",
and a "does this name already exist?" check written that way answers no and then overwrites
something. This is why the mutation lock normalises to NFC before keying — a live property of
the user's machine, not a portability footnote.
`],
  [`${H}/unicode-names/${NFC_NAME}`, `# resume (precomposed)

The composed sibling of the decomposed file next to this one — one U+00E9 where the other has two
code points. Same appearance, two bytes shorter, and on this volume the filesystem treats them as
the same name.

They coexist here only because the rest of the basename differs. Give them the same base and
there is exactly one file.
`],
  [`${H}/unicode-names/رسالة-rtl.md`, `# رسالة

Right-to-left filename. Renders with the direction reversed in most UI; the bytes are in logical
order. A UI that reverses it again gets a name nobody can retype.
`],

  // --- awkward but legal names --------------------------------------------------------------
  [`${H}/awkward-names/a file with spaces.md`, `# Spaces

Legal everywhere, breaks anything that builds a command line by concatenation. §10 bans shell
execution partly because of this file.
`],
  [`${H}/awkward-names/hash#in#name.md`, `# Hashes

A \`#\` is a fragment separator in a URL. If a path reaches the client through a URL without
encoding, everything after the first hash is gone.
`],
  [`${H}/awkward-names/percent%20encoded.md`, `# Percent

This file is literally named \`percent%20encoded.md\`. Decode a path twice and you get
\`percent encoded.md\` — a different file, which may also exist.
`],
  [`${H}/awkward-names/question?mark.md`, `# Question mark

A query-string separator, same failure as the hash.
`],
  [`${H}/awkward-names/quote'apostrophe.md`, `# Apostrophe

Breaks naive single-quoted shell arguments and naive SQL alike.
`],
  [`${H}/awkward-names/back\\slash.md`, `# Backslash

Legal in a POSIX filename. A separator on Windows, and an escape character in most string
handling.
`],
  [`${H}/awkward-names/trailing.dots...md`, `# Trailing dots

The extension test has to find \`.md\` at the end and not be confused by the run before it.
`],
  [`${H}/awkward-names/-leading-dash.md`, `# Leading dash

Any tool that passes this as an argument reads it as a flag.
`],
  [`${H}/awkward-names/${LONG_NAME}`, `# A 249-byte filename

Legal — NAME_MAX is 255 bytes on this volume. **A conflict artifact adds 28 bytes to a basename.**
Rescuing an edit to this file therefore needs a name that does not exist, and the app must check
the limit in *bytes* before generating one rather than discovering it at the open.
`],
  [`${H}/awkward-names/UPPERCASE.md`, `# UPPERCASE

This volume is case-insensitive. A rename to \`uppercase.md\` is a *case-only* rename and must be
detected by comparing \`(dev, ino)\`, never by comparing the two strings — a string comparison says
"different name, destination is free", and the exclusive-rename check then finds the destination
occupied by this very file.
`],

  // --- content edges ----------------------------------------------------------------------------
  [`${H}/content-edges/empty.md`, ''],
  [`${H}/content-edges/no-trailing-newline.md`, '# No trailing newline\n\nThe last byte of this file is a full stop.'],
  [`${H}/content-edges/crlf-line-endings.md`,
    '# CRLF\r\n\r\nEvery line ending in this file is a carriage return and a line feed.\r\n\r\nAn editor that normalises them on save rewrites every line of the file, which turns a one-word\r\nedit into a whole-file diff and makes the conflict hash differ for no reason.\r\n'],
  [`${H}/content-edges/lone-cr-line-endings.md`,
    '# Lone CR\r\rClassic Mac line endings. Nothing produces these any more, and they still exist.\r'],
  [`${H}/content-edges/bom-at-start.md`,
    '﻿# Byte order mark\n\nThis file begins with U+FEFF. Strip it on read and write it back without, and the file has\nsilently changed. Keep it and the first heading may not parse.\n'],
  [`${H}/content-edges/one-very-long-line.md`,
    `# One very long line\n\n${'the intake curve is not weather-shaped and the packing line cannot be argued with. '.repeat(4000)}\n`],
  [`${H}/content-edges/thousands-of-short-lines.md`,
    `# Many lines\n\n${Array.from({ length: 12000 }, (_, i) => `- line ${i + 1}`).join('\n')}\n`],
  [`${H}/content-edges/README.md`, `# Content edges

The theme: **the bytes on disk are the truth.** Anything the app "helpfully" normalises — line
endings, a BOM, a trailing newline, Unicode form — is a change to the file that the user did not
ask for and cannot see.

Two files here are about size rather than shape: \`just-under-the-cap.md\` and
\`over-the-cap.md\` sit either side of \`MAX_EDITABLE_BYTES\` (2 MiB). The first must open. The
second must be **refused with a reason**, and must never open truncated.
`],

  // --- already conflicted -------------------------------------------------------------------
  [`${H}/already-conflicted/harvest-plan.md`, `# Harvest plan

**This is the canonical file.** Its conflict sibling sits next to it.

Pick order: Lodi, Paulared, Ginger Gold, Honeycrisp, Gala, McIntosh, Cortland, Northern Spy.
`],
  [`${H}/already-conflicted/harvest-plan.conflict-20260806-134700-a3f7.md`,
    `# Harvest plan

**This is a rescue file** — the shape the app writes when it cannot save your edit. It exists in
the mock tree so the two-pane resolution screen has something real to open.

Pick order: Lodi, Paulared, Ginger Gold, **Honeycrisp moved after Gala**, Gala, McIntosh,
Cortland, Northern Spy.

It must never be treated as ordinary content: not a card, not an inbox item, not a project, and
never itself given a conflict child.
`],
  [`${H}/links/hardlink-original.md`, `# The first name

This file has a second name — \`hardlink-copy.md\` in this folder — and both point at one inode.
\`st_nlink\` is 2.

An atomic write to either name replaces the directory entry and leaves the other name pointing at
the old bytes, so the two silently stop being the same file. §13.6 refuses to write through a file
with more than one name rather than doing that quietly.
`],

  [`${H}/already-conflicted/README.md`, `# Already conflicted

One canonical file, one rescue artifact, already on disk. The resolution surface should offer
Keep Mine / Keep Theirs / Keep Both, end with exactly one file at \`harvest-plan.md\`, and keep
the loser rather than deleting it.
`],

  // --- ignored ---------------------------------------------------------------------------------
  [`${H}/ignored/node_modules/some-package/README.md`, '# Never indexed\n'],
  [`${H}/ignored/node_modules/some-package/lib/index.md`, '# Never indexed\n'],
  [`${H}/ignored/dist/build-output.md`, '# Never indexed\n'],
  [`${H}/ignored/.hidden-folder/secret.md`, '# Never indexed\n'],
  [`${H}/ignored/Something.app/Contents/notes.md`, '# Never indexed — inside a bundle\n'],
  [`${H}/ignored/.DS_Store`, 'not really a DS_Store'],
  [`${H}/ignored/x-node_modules-not-really.md`, `# Indexed

A name that *contains* an ignored word is not ignored. The ignore list matches whole path
segments, not substrings.
`],

  // --- not markdown -----------------------------------------------------------------------------
  [`${H}/not-markdown/photo.png`, 'PNG-ish bytes, not a real image'],
  [`${H}/not-markdown/spreadsheet.csv`, 'farm,bushels\nHollis,11000\nBray,6300\n'],
  [`${H}/not-markdown/notes.markdown`, `# Not our extension

\`.markdown\` is deliberately excluded. So is \`.mdx\`. \`isMarkdown()\` is the only extension test
in the codebase and it accepts \`.md\` only.
`],
  [`${H}/not-markdown/notes.mdx`, '# Also excluded\n'],

  // --- deliberately hostile content -------------------------------------------------------------
  //
  // Added for P7. The mock soil was built for FILESYSTEM hazards and a later pass added markdown
  // constructs; neither covered *attacks*, so build plan §9's named fixture list — remote image,
  // javascript:, java\tscript:, &#106;avascript:, protocol-relative //host, raw <script>, an .html
  // vault file, an .svg carrying script — existed nowhere. Every one of these is inert if the app
  // is correct, and each is a live defect if it is not.
  [`${M}/README.md`, `# Deliberately hostile content

Nothing in this folder is dangerous **to you** — it is dangerous to an app that gets §8 or §9
wrong. Each file carries one attack, so a failure names itself.

| File | What it tries |
|---|---|
| \`links.md\` | every way to smuggle a script into a link destination |
| \`images.md\` | images that fetch from somewhere else, which is a tracking pixel |
| \`raw-html.md\` | HTML tags inside markdown, including a script tag |
| \`page.html\` | an HTML file in the tree — must download, never render |
| \`script-carrier.svg\` | an SVG containing a script — must NEVER be \`image/svg+xml\` |

If any of them does something visible, that is the bug.
`],

  [`${M}/links.md`, `# Links that should all be plain text

[plain javascript](javascript:alert(1))
[tab split](java\tscript:alert(1))
[decimal entity](&#106;avascript:alert(1))
[hex entity](&#x6A;avascript:alert(1))
[double encoded](&amp;#106;avascript:alert(1))
[named colon](javascript&colon;alert(1))
[percent encoded](%6aavascript:alert(1))
[mixed case](JaVaScRiPt:alert(1))
[leading space]( javascript:alert(1))
[protocol relative](//evil.example.com/x)
[data uri](data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==)
[vbscript](vbscript:msgbox(1))
[local file](file:///etc/passwd)

And two that SHOULD work, so the test can tell inert from broken:

[an ordinary site](https://example.com/)
[a file next door](./raw-html.md)
`],

  [`${M}/images.md`, `# Images that must never be fetched

![remote](https://tracker.example.com/pixel.gif)
![protocol relative](//tracker.example.com/pixel.gif)
![data uri](data:image/gif;base64,R0lGODlhAQABAAAAACw=)

And one that should load, being a real file in this tree:

![a real one](../not-markdown/real-photo.png)
`],

  [`${M}/raw-html.md`, `# Raw HTML inside markdown

<script>window.__soilViewerWasCompromised = true</script>
<img src=x onerror="window.__soilViewerWasCompromised = true">
<iframe src="https://example.com"></iframe>
<a href="javascript:alert(1)">a hand-written link</a>
<style>body { display: none }</style>

Ordinary inline HTML, which 10% of the real tree carries and must still read as text:

Recorded <b>before</b> the vote, with a <sub>note</sub>.
`],

  [`${M}/page.html`, `<!doctype html>
<html><head><title>Not a document this app renders</title></head>
<body><script>window.__soilViewerWasCompromised = true</script>
<p>If you are reading this rendered, the file endpoint served it as HTML.</p>
</body></html>
`],

  [`${M}/script-carrier.svg`, `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">
  <script type="application/javascript">window.__soilViewerWasCompromised = true</script>
  <rect width="100" height="100" fill="crimson"/>
</svg>
`],
  [`${H}/not-markdown/config.json`, '{ "not": "a document" }\n'],
  [`${H}/not-markdown/README.md`, `# Not markdown

The app writes non-markdown bytes in exactly one situation: recursive copy, byte for byte,
unmodified. Everything else refuses at the chokepoint regardless of what the client asked for.
`],
]

/**
 * Sixteen path segments below the root, counted the way the real tree's depth was counted on
 * 2026-08-08 — `zz-hazards` + `deep` + thirteen levels + the file.
 */
const DEEP_PATH = `${H}/deep/${Array.from({ length: 13 }, (_, i) => `level-${i + 1}`).join('/')}/bottom.md`

export const DEEP_FILE: PlainFile = [DEEP_PATH, `# The bottom

Sixteen levels from the root, which is as deep as the real tree goes.

A recursive copy of a folder near the top can push a path here past \`PATH_MAX\`. The pre-flight
walk measures the longest path **before** writing a byte, for exactly this reason.
`]

/** Everything that needs more than `writeFile`. Order matters: link targets first. */
export const SPECIAL_ENTRIES: readonly SpecialEntry[] = [
  {
    path: `${H}/not-markdown/real-photo.png`,
    why: 'A REAL 1x1 PNG — the neighbouring photo.png is the string "PNG-ish bytes", which cannot exercise the §9 endpoint at all',
    kind: {
      type: 'bytes',
      // A 1x1 transparent PNG, 70 bytes, signature first. Small enough to sit in source and real
      // enough that a browser decodes it, which is the point: an image fixture that is not an
      // image proves nothing about an endpoint whose whole job is content type.
      bytes: [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0,
        1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 207,
        192, 80, 15, 0, 4, 133, 1, 128, 132, 169, 140, 33, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66,
        96, 130],
    },
  },
  {
    path: `${H}/content-edges/invalid-utf8.md`,
    why: 'Bytes that are not valid UTF-8 — reading as a string replaces them and a save would write the replacement back',
    kind: {
      type: 'bytes',
      // "# Broken\n\n" then a lone 0xFF and a truncated multi-byte sequence.
      bytes: [0x23, 0x20, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x0a, 0x0a,
        0xff, 0xfe, 0xe2, 0x28, 0xa1, 0x0a],
    },
  },
  {
    path: `${H}/content-edges/nul-byte-inside.md`,
    why: 'A NUL byte in the middle of a text file — invisible in every editor, and it truncates anything using C strings',
    kind: {
      type: 'bytes',
      bytes: [0x23, 0x20, 0x4e, 0x55, 0x4c, 0x0a, 0x0a, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65,
        0x00, 0x61, 0x66, 0x74, 0x65, 0x72, 0x0a],
    },
  },
  {
    path: `${H}/content-edges/just-under-the-cap.md`,
    why: 'Just under MAX_EDITABLE_BYTES (2 MiB) — must open normally',
    kind: { type: 'filled', size: 2 * 1024 * 1024 - 4096, unit: 'the cap minus 4 KiB' },
  },
  {
    path: `${H}/content-edges/over-the-cap.md`,
    why: 'Over MAX_EDITABLE_BYTES — must be refused with a reason, never opened truncated',
    kind: { type: 'filled', size: 2 * 1024 * 1024 + 4096, unit: 'the cap plus 4 KiB' },
  },
  {
    path: `${H}/links/link-to-a-file-inside.md`,
    why: 'A symlink to a real document in this tree — a write must resolve it, containment-check the target, and refuse a multiply-linked file',
    kind: { type: 'symlink', target: '../../README.md', relative: true },
  },
  {
    path: `${H}/links/link-to-a-folder-inside`,
    why: 'A symlink to a directory in this tree — the walk must not follow it, or it indexes the same files twice',
    kind: { type: 'symlink', target: '../already-conflicted', relative: true },
  },
  {
    path: `${H}/links/link-escaping-the-tree`,
    why: 'A symlink pointing outside the registered folder entirely — following it is how a write lands somewhere it was never allowed',
    kind: { type: 'symlink', target: '/etc', relative: false },
  },
  {
    path: `${H}/links/broken-link.md`,
    why: 'A symlink whose target does not exist — stat throws, lstat does not, and code that only uses stat treats it as missing',
    kind: { type: 'symlink', target: './nothing-is-here.md', relative: true },
  },
  {
    path: `${H}/links/hardlink-copy.md`,
    why: 'A second name for the same inode (st_nlink = 2) — copying by fs.link would silently share bytes, and an atomic write breaks the link without warning',
    // Links to a file of its own rather than to the conflict pair's canonical document.
    //
    // It pointed at `already-conflicted/harvest-plan.md` in the first draft, and the first
    // end-to-end drive refused `conflict.resolve` on it with `HARDLINKED` — correctly: §13.6 will
    // not write through a file with more than one name. The app was right and the fixture had
    // made its own conflict pair unresolvable. Worth keeping the note: a hazard placed on top of
    // another hazard tests neither of them.
    kind: { type: 'hardlink', to: `${H}/links/hardlink-original.md` },
  },
  {
    path: `${H}/permissions/read-only.md`,
    why: 'Mode 0444 — rename(2) succeeds over a non-writable file when the parent is writable, so the mode must be checked explicitly or a save reports success it did not earn',
    kind: {
      type: 'mode',
      mode: 0o444,
      body: `# Read only

This file is mode 0444. The parent directory is writable, which means \`rename(2)\` will happily
replace it. The write path checks the destination's mode before it gets that far, and opens the
file read-only with a visible reason.
`,
    },
  },
  {
    path: `${H}/permissions/unreadable.md`,
    why: 'Mode 0000 — the read fails, and a failed read must produce a named error rather than an empty document you can then save over',
    kind: { type: 'mode', mode: 0o000, body: '# You should not be able to read this\n' },
  },
  {
    path: `${H}/permissions/read-only-folder`,
    why: 'A directory at mode 0555 — writes into it fail, and the failure must be reported rather than swallowed',
    kind: { type: 'dir-mode', mode: 0o555 },
  },
  {
    path: `${H}/content-edges/an-empty-folder`,
    why: 'An empty directory — a lane that is empty must be hidden, not shown as a broken card',
    kind: { type: 'empty-dir' },
  },
]

/**
 * NOTABLE PATHS — what a test may rely on being there, and what must be true of it.
 *
 * Kept deliberately short. This is the contract between the generator and anything that reads the
 * tree; the rest of the tree is scenery and may change freely.
 */
export interface Notable {
  readonly path: string
  readonly expect: 'file' | 'dir' | 'symlink' | 'unreadable' | 'read-only'
  readonly note: string
}

export const NOTABLE: readonly Notable[] = [
  { path: 'README.md', expect: 'file', note: 'says in plain language that none of this is real' },
  { path: '02-projects/cold-store-expansion/00-context/m-thread-cold-store-expansion.md', expect: 'file', note: 'a long realistic document, for reading on a screen' },
  { path: `${H}/already-conflicted/harvest-plan.md`, expect: 'file', note: 'canonical half of a conflict pair' },
  { path: `${H}/already-conflicted/harvest-plan.conflict-20260806-134700-a3f7.md`, expect: 'file', note: 'the rescue artifact, for the resolution screen' },
  { path: `${H}/content-edges/over-the-cap.md`, expect: 'file', note: 'above MAX_EDITABLE_BYTES; must be refused, never truncated' },
  { path: `${H}/content-edges/just-under-the-cap.md`, expect: 'file', note: 'below the cap; must open' },
  { path: `${H}/links/link-escaping-the-tree`, expect: 'symlink', note: 'points outside the root; must never be followed for a write' },
  { path: `${H}/links/hardlink-copy.md`, expect: 'file', note: 'st_nlink = 2; copy by content, never by link' },
  { path: `${H}/permissions/unreadable.md`, expect: 'unreadable', note: 'mode 0000; a failed read must not become an empty document' },
  { path: `${H}/permissions/read-only.md`, expect: 'read-only', note: 'mode 0444; rename would succeed over it, so the mode is checked' },
  { path: `${H}/unicode-names/${NFD_NAME}`, expect: 'file', note: 'decomposed form; readdir hands this form back, and a raw string compare against the composed name says "different file" where the volume says "same file"' },
  { path: `${H}/unicode-names/${NFC_NAME}`, expect: 'file', note: 'precomposed sibling of the above' },
  { path: `${H}/awkward-names/${LONG_NAME}`, expect: 'file', note: '249-byte basename; legal, but its conflict sibling would be 279 and fail ENAMETOOLONG' },
  { path: DEEP_PATH, expect: 'file', note: 'sixteen levels, matching the real tree' },
]

export const SPINE_FILES = SPINE
